const PATIENTS_DATA = [
   {
      idUtilisateur: "100",
      cin: "BE77364",
      nom: "amine",
      prenom: "moral",
      email: "amine@mail.com",
      situationFamilliale: "celibataire",
      genre: "homme",
      tel: "0976656454",
      adresse: "casablanca, 3533\r\nRYTC 968786",
      imageProfile: "/uploads/images/625a247febf42.jpg",
      type: "patient",
   },
   {
      idUtilisateur: "200",
      cin: "TR3456",
      nom: "rachid",
      prenom: "kafi",
      email: "rachid@mail.com",
      situationFamilliale: "celibataire",
      genre: "homme",
      tel: "09765432134",
      adresse: "casablanca, 33\r\nIUY 968786",
      imageProfile: "/uploads/images/625a24d373d6d.jpg",
      type: "patient",
   },
   {
      idUtilisateur: "543",
      cin: "BE77364",
      nom: "amine",
      prenom: "moral",
      email: "amine@mail.com",
      situationFamilliale: "celibataire",
      genre: "homme",
      tel: "0976656454",
      adresse: "casablanca, 3533\r\nRYTC 968786",
      imageProfile: "/uploads/images/625a247febf42.jpg",
      type: "patient",
   },
   {
      idUtilisateur: "743",
      cin: "TR3456",
      nom: "rachid",
      prenom: "kafi",
      email: "rachid@mail.com",
      situationFamilliale: "celibataire",
      genre: "homme",
      tel: "09765432134",
      adresse: "casablanca, 33\r\nIUY 968786",
      imageProfile: "/uploads/images/625a24d373d6d.jpg",
      type: "patient",
   },
   {
      idUtilisateur: "2456",
      cin: "BE77364",
      nom: "amine",
      prenom: "moral",
      email: "amine@mail.com",
      situationFamilliale: "celibataire",
      genre: "femme",
      tel: "0976656454",
      adresse: "casablanca, 3533\r\nRYTC 968786",
      imageProfile: "/uploads/images/625a247febf42.jpg",
      type: "patient",
   },
   {
      idUtilisateur: "6324",
      cin: "TR3456",
      nom: "rachid",
      prenom: "kafi",
      email: "rachid@mail.com",
      situationFamilliale: "celibataire",
      genre: "homme",
      tel: "09765432134",
      adresse: "casablanca, 33\r\nIUY 968786",
      imageProfile: "/uploads/images/625a24d373d6d.jpg",
      type: "patient",
   },
];

export default PATIENTS_DATA;
